from PyQt5 import QtCore, QtGui, QtWidgets


class examplePopup(QtWidgets.QWidget):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.initUI()

    def initUI(self):
        self.lblName = QLabel(self.name, self)


class ExamplePopup(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.le = QLineEdit(self)
        self.le.resize(150, 20)
        self.le.move(10, 10)
        self.le2 = QLineEdit(self)
        self.le2.resize(150, 20)
        self.le2.move(10, 30)
        self.le3 = QLineEdit(self)
        self.le3.resize(150, 20)
        self.le3.move(10, 50)
        self.le4 = QLineEdit(self)
        self.le4.resize(150, 20)
        self.le4.move(10, 70)
        self.le5 = QLineEdit(self)
        self.le5.resize(150, 20)
        self.le5.move(10, 90)
        self.le6 = QLineEdit(self)
        self.le6.resize(150, 20)
        self.le6.move(10, 110)
        self.le7 = QLineEdit(self)
        self.le7.resize(150, 20)
        self.le7.move(10, 130)
        self.le8 = QLineEdit(self)
        self.le8.resize(150, 20)
        self.le8.move(10, 150)
        self.le9 = QLineEdit(self)
        self.le9.resize(150, 20)
        self.le9.move(10, 170)
        self.le10 = QLineEdit(self)
        self.le10.resize(150, 20)
        self.le10.move(10, 190)
        self.le.setText("ID")
        self.le2.setText("NAMETM")
        self.le3.setText("DIVISION")
        self.le4.setText("IKLASSVOLTAGED")
        self.le5.setText("PARTVL")
        self.le6.setText("NAMEVL")
        self.le7.setText("MANAGE")
        self.le8.setText("TYPETM")
        self.le9.setText("DATEEDIT")
        self.le10.setText("KODTM")
        self.btn = QPushButton(self)
        self.btn.resize(100, 20)
        self.btn.move(10, 230)
        self.btn.setText("Добавить")


class Example(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.x = 0
        self.setGeometry(300, 300, 700, 700)
        self.setWindowTitle('Фокусы с арифметикой')
        self.lbl = QLabel(self)
        self.lbl.move(50, 35)
        self.lbl.resize(600, 600)
        self.lbl1 = QLabel(self)
        self.lbl1.resize(1000, 20)
        self.lbl1.move(0, 20)
        self.btn = QPushButton(self)
        self.btn.move(20, 0)
        self.btn.resize(20, 20)
        self.btn.setText("->")
        self.btn.clicked.connect(self.run)
        self.btn1 = QPushButton(self)
        self.btn1.resize(20, 20)
        self.btn1.setText("<-")
        self.btn1.clicked.connect(self.run)
        self.lst = []
        string = "Из таблицы ближайших опор надо указать то как вы хотите "
        string += "назвать свою опору, нажать кнопку “переименовать”"
        string2 = "Так же можно указать до какого расстояния будет показываться "
        string2 += "опоры, сколько будет показываться ближайших опор."
        self.lst1 = ["Выбор изображения",
                     "Указать директорию изображений",
                     "Выбрать силу тока показываемых опор",
                     string,
                     string2]
        absoluteFilePath = os.path.abspath(__file__)
        self.path_dir = os.path.split(absoluteFilePath)[0]
        for i in range(2, 7):
            self.lst.append(self.path_dir + f"\Фото{str(i)}.jpg")
        self.lbl.setPixmap(QPixmap(self.lst[self.x]))
        self.lbl1.setText(self.lst1[self.x])

    def run(self):
        if self.x < 4 and self.sender().text() == "->":
            self.x += 1
        if self.x > 1 and self.sender().text() == "<-":
            self.x -= 1
        self.lbl.setPixmap(QPixmap(self.lst[self.x]))
        self.lbl1.setText(self.lst1[self.x])
        

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDir.setMinimumSize(QtCore.QSize(150, 31))
        self.pushButtonDir.setMaximumSize(QtCore.QSize(150, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonDir.setFont(font)
        self.pushButtonDir.setObjectName("pushButtonDir")
        self.verticalLayout.addWidget(self.pushButtonDir)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setMinimumSize(QtCore.QSize(300, 0))
        self.listView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(80, 31))
        self.label.setMaximumSize(QtCore.QSize(16777215, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(300, 31))
        self.label_3.setMaximumSize(QtCore.QSize(300, 36))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimumSize(QtCore.QSize(91, 31))
        self.spinBox.setMinimum(100)
        self.spinBox.setMaximum(6999)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_5.addWidget(self.spinBox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(130, 31))
        self.label_4.setMaximumSize(QtCore.QSize(130, 36))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMinimumSize(QtCore.QSize(51, 31))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setSingleStep(1)
        self.spinBox_2.setProperty("value", 15)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_5.addWidget(self.spinBox_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(160, 31))
        self.label_5.setMaximumSize(QtCore.QSize(160, 36))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.checkBox04 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox04.setObjectName("checkBox04")
        self.verticalLayout_5.addWidget(self.checkBox04)
        self.checkBox6_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox6_10.setObjectName("checkBox6_10")
        self.verticalLayout_5.addWidget(self.checkBox6_10)
        self.checkBox110 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox110.setObjectName("checkBox110")
        self.verticalLayout_5.addWidget(self.checkBox110)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(416, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl = QtWidgets.QLabel(self.centralwidget)
        self.lbl.setMinimumSize(QtCore.QSize(351, 351))
        self.lbl.setObjectName("lbl")
        self.gridLayout_3.addWidget(self.lbl, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.group = QtWidgets.QButtonGroup(self.centralwidget)
        self.group.setObjectName("group")
        self.rbtn1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn1.setMinimumSize(QtCore.QSize(80, 31))
        self.rbtn1.setMaximumSize(QtCore.QSize(80, 31))
        self.rbtn1.setObjectName("rbtn1")
        self.group.addButton(self.rbtn1)
        self.gridLayout_4.addWidget(self.rbtn1, 0, 0, 1, 1)
        self.rbtn2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn2.setMinimumSize(QtCore.QSize(80, 31))
        self.rbtn2.setMaximumSize(QtCore.QSize(80, 31))
        self.rbtn2.setObjectName("rbtn2")
        self.group.addButton(self.rbtn2)
        self.gridLayout_4.addWidget(self.rbtn2, 0, 1, 1, 1)
        self.rbtn3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn3.setMinimumSize(QtCore.QSize(80, 31))
        self.rbtn3.setMaximumSize(QtCore.QSize(80, 31))
        self.rbtn3.setObjectName("rbtn3")
        self.rbtn3.setChecked(True)
        self.group.addButton(self.rbtn3)
        self.gridLayout_4.addWidget(self.rbtn3, 0, 2, 1, 1)
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setObjectName("lbl2")
        self.gridLayout_4.addWidget(self.lbl2, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(551, 351))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditTo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTo.setReadOnly(True)
        self.lineEditTo.setObjectName("lineEditTo")
        self.verticalLayout_2.addWidget(self.lineEditTo)
        self.lineEditFrom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFrom.setObjectName("lineEditFrom")
        self.verticalLayout_2.addWidget(self.lineEditFrom)
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setMinimumSize(QtCore.QSize(150, 31))
        self.pushButton1.setMaximumSize(QtCore.QSize(160, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.verticalLayout_2.addWidget(self.pushButton1)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonDir.setText(_translate("MainWindow", "Выберите директорию"))
        self.label_3.setText(_translate("MainWindow", "Введите максимальное растояние(1-6999 в метрах)"))
        self.label_4.setText(_translate("MainWindow", "Показать опор(1-99)"))
        self.label_5.setText(_translate("MainWindow", "Искать по уровню напряжения"))
        self.checkBox04.setText(_translate("MainWindow", "0,4-0,22-0,23,0,38"))
        self.checkBox6_10.setText(_translate("MainWindow", "6-10-20-35"))
        self.checkBox110.setText(_translate("MainWindow", "110"))
        self.rbtn1.setText(_translate("MainWindow", "Схема"))
        self.rbtn2.setText(_translate("MainWindow", "Спутниk"))
        self.rbtn3.setText(_translate("MainWindow", "Гибрид"))
        self.lbl2.setText(_translate("MainWindow", "Карта"))
        self.pushButton1.setText(_translate("MainWindow", "Сменить имя"))
        self.menu.setTitle(_translate("MainWindow", "Помощь"))
        self.menu_2.setTitle(_translate("MainWindow", "Бонус"))
        self.action.setText(_translate("MainWindow", "О программе"))
        self.action_2.setText(_translate("MainWindow", "Про автора"))
        self.action_3.setText(_translate("MainWindow", "Шрифт"))
